// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_character_bluealien = "CgkI9Kvawr4aEAIQBw"; // <GPGSID>
        public const string achievement_100m = "CgkI9Kvawr4aEAIQAg"; // <GPGSID>
        public const string achievement_500m = "CgkI9Kvawr4aEAIQCA"; // <GPGSID>
        public const string achievement_character_greenman = "CgkI9Kvawr4aEAIQBg"; // <GPGSID>
        public const string achievement_200m = "CgkI9Kvawr4aEAIQAw"; // <GPGSID>
        public const string leaderboard_high_score = "CgkI9Kvawr4aEAIQAQ"; // <GPGSID>
        public const string achievement_300m = "CgkI9Kvawr4aEAIQBA"; // <GPGSID>
        public const string achievement_character_devil = "CgkI9Kvawr4aEAIQBQ"; // <GPGSID>

}

